version: "3.8"
services:
    notepad_app:
        container_name: notepad_app
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        expose:
            - 9000
        volumes:
            - .:/usr/src/app
            - ./public:/usr/src/app/public
        depends_on:
            - notepad_mysql
        networks:
            - app_network
    notepad_nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        volumes:
            - ./public:/usr/src/app/public
        ports:
            - 8000:80
        depends_on:
            - notepad_app
        environment:
            NGINX_FPM_HOST: notepad_app
            NGINX_ROOT: /usr/src/app/public
        networks:
            - app_network
    adminer:
        container_name: adminer
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - notepad_mysql
        networks:
            - app_network
    notepad_mysql:
        container_name: mysql
        image: mysql:8.0.20
        restart: always
        platform: linux/x86_64
        volumes:
            - ./storage/db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app_network
    notepad_redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - app_network
    notepad_elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=${ELASTICSEARCH_SECURITY}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - app_network
    notepad_kibana:
        image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=${APP_URL}:9200
        links:
            - notepad_elasticsearch
        depends_on:
            - notepad_elasticsearch
        networks:
            - app_network
        deploy:
            resources:
                limits:
                    cpus: '2.0'
                reservations:
                    cpus: '1.0'
networks:
    app_network:
        driver: bridge
